/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['nav{box-shadow:0 1px 5px #666}section{position:relative;padding-top:90px;padding-bottom:90px}section.background-gray-lighter{background:#cdcdcd}.padding--small{padding-top:30px;padding-bottom:30px}.text-intro{background:transparent linear-gradient(180deg,#0275d8,#6795ab) repeat scroll 0 0;text-align:center;color:#fff}.text-intro h1{font-weight:700}.text-intro a{color:#fff;text-decoration:underline}.text-intro h1,.text-intro h2,.text-intro h3,.text-intro h4{color:#fff}.text-intro span{color:#2b7551}'];
//# sourceMappingURL=app.component.css.ngstyle.js.map